name: Test Action

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}

    env:
      GITHUB_TOKEN: ${{ github.token }}

    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Disable EOL conversions
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 10.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 10.x

      - name: npm install
        run: npm install

      - name: npm lint
        run: npm run format-check

      - name: npm test
        run: npm test
